#pragma config(Sensor, in1,    rgLight,        sensorAnalog)
#pragma config(Sensor, dgtl10, beaconMode,     sensorDigitalOut)
#pragma config(Sensor, dgtl11, readingTime,    sensorDigitalOut)
#pragma config(Sensor, dgtl12, scan,           sensorDigitalOut)
#pragma config(Motor,  port2,           motR,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           motL,          tmotorServoStandard, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (true)
{
	writeDebugStreamLine("beacon = %d", SensorValue[rgLight]);
	wait1Msec(100);
}
}
