#pragma config(Sensor, in1,     irIntensity,     sensorAnalog)
#pragma config(Sensor, dgtl1,   sonarSensor,     sensorSONAR_cm)
#pragma config(Sensor, dgtl5,   bumper,          sensorTouch)
#pragma config(Sensor, dgtl6,   armLimit,        sensorTouch)
#pragma config(Sensor, dgtl8,   freqSelect,      sensorDigitalOut)
#pragma config(Sensor, dgtl9,   exposeCtrl,      sensorDigitalOut)
#pragma config(Sensor, dgtl10,  counterReset,    sensorDigitalOut)
#pragma config(Motor,  port1,   armMotor,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,   leftMotor,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,  rightMotor,      tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* ============================================================================
 * E10 Robot Project - Search & Rescue
 *   Task 1: Find the red  (1 kHz) beacon and stop next to it
 *   Task 2: Deploy arm to press the pushbutton on top (turn red beacon off)
 *   Task 3: Find the green (10 kHz) beacon
 *   Task 4: Push the green beacon across the starting line, using bumper /
 *           ultrasonic to avoid walls and find the arena opening
 *
 *   Based on the provided GOTO_BEACON sample; extended with a state machine,
 *   arm control, bumper + ultrasonic behaviours, and dual-frequency sensing.
 * ========================================================================== */

/* ---------- IRB tuning parameters ---------- */
int ambient_level     = 200;    // below this = nothing visible, search
int slow_level        = 5000;   // above this = beacon is getting near, slow
int stop_level        = 6000;   // above this = essentially on the beacon
int expose_time       = 5;      // 3..8 ms, gain of the IR front-end
int steer_sensitivity = 20;     // heading gain (per detector offset from #4)
int forward_speed     = 35;
int slow_speed        = 25;
int spin_speed        = 50;     // fast spin: backup/recovery turns
int search_spin_speed = 22;     // slow spin: IR search; lower = better detector dwell

/* ---------- distance / timing ---------- */
int wall_cm           = 20;     // ultrasonic wall-avoid threshold
int near_beacon_cm    = 15;     // commit-to-target distance
int arm_drop_ms       = 1200;   // fallback time if arm limit switch never hits
int arm_raise_ms      = 1000;
int backup_ms         = 700;
int turn_180_ms       = 1400;
int push_out_ms       = 4000;   // worst-case push across starting line

/* ---------- globals shared with the IRB routines ---------- */
int PD0,PD1,PD2,PD3,PD4,PD5,PD6,PD7,PD_sum;
int max_val, max_no = 0;

/* ---------- status display state ---------- */
int  currentFreq  = 0;
bool irWasVisible = false;

/* ==========================================================================
 * Status display
 *   Top LCD line  = current high-level state (set via setStatusTop)
 *   Bottom line   = live IR telemetry: "f<freq> s=<sum> D<detector>" when
 *                   IR is visible, "NO IR sum=<sum>" when below ambient.
 *   Debug stream  = same info; printed at every state change and on every
 *                   IR-acquired/IR-lost transition.
 *
 *   No LCD connected?  The display* calls are silent no-ops; the debug
 *   stream still works when tethered to the RobotC IDE.
 * ========================================================================== */
void setStatusTop(string s){
    bLCDBacklight = true;
    clearLCDLine(0);
    displayLCDString(0, 0, "%s", s);
    writeDebugStreamLine("STATE: %s", s);
}

void showIRTelemetry(){
    string buf;
    if(PD_sum < ambient_level){
        sprintf(buf, "NO IR sum=%d", PD_sum);
    } else {
        sprintf(buf, "f%d s=%d D%d", currentFreq, PD_sum, max_no);
    }
    clearLCDLine(1);
    displayLCDString(1, 0, "%s", buf);

    bool nowVisible = (PD_sum >= ambient_level);
    if(nowVisible != irWasVisible){
        irWasVisible = nowVisible;
        if(nowVisible)
            writeDebugStreamLine("IR ACQUIRED f=%d sum=%d D=%d",
                                  currentFreq, PD_sum, max_no);
        else
            writeDebugStreamLine("IR LOST     f=%d sum=%d",
                                  currentFreq, PD_sum);
    }
}

/* ==========================================================================
 * Low-level drive helpers
 * ========================================================================== */
int limit_pwm(int v){
    if(v >  127) return  127;
    if(v < -127) return -127;
    return v;
}
void drive(int left, int right){
    motor[leftMotor]  = limit_pwm(left);
    motor[rightMotor] = limit_pwm(right);
}
void stopDrive(){ drive(0,0); }

/* ==========================================================================
 * IRB access - unchanged semantics from the sample GOTO_BEACON
 * ========================================================================== */
int Expose_and_read(){
    SensorValue[exposeCtrl] = 1;   // close shutter, advance detector counter
    delay(5);
    SensorValue[exposeCtrl] = 0;   // open shutter, expose
    delay(expose_time);
    return SensorValue[irIntensity];
}

void ReadPD(){
    SensorValue[exposeCtrl]   = 1;
    SensorValue[counterReset] = 1; // reset active detector to #0
    SensorValue[counterReset] = 0;
    delay(5);
    SensorValue[exposeCtrl]   = 0;
    delay(expose_time);
    PD0 = SensorValue[irIntensity];
    PD1 = Expose_and_read();
    PD2 = Expose_and_read();
    PD3 = Expose_and_read();
    PD4 = Expose_and_read();
    PD5 = Expose_and_read();
    PD6 = Expose_and_read();
    PD7 = Expose_and_read();
    PD_sum = PD0+PD1+PD2+PD3+PD4+PD5+PD6+PD7;
}

void Find_max(){
    max_val = PD0; max_no = 0;
    if(PD1>max_val){max_val=PD1;max_no=1;}
    if(PD2>max_val){max_val=PD2;max_no=2;}
    if(PD3>max_val){max_val=PD3;max_no=3;}
    if(PD4>max_val){max_val=PD4;max_no=4;}
    if(PD5>max_val){max_val=PD5;max_no=5;}
    if(PD6>max_val){max_val=PD6;max_no=6;}
    if(PD7>max_val){max_val=PD7;max_no=7;}
}

/* ==========================================================================
 * Frequency selection  (0 = 1kHz red,  1 = 10kHz green)
 *   After switching, allow the analog front-end a moment to settle before
 *   trusting PD readings.
 * ========================================================================== */
void setFreq(int f){
    SensorValue[freqSelect] = f;
    currentFreq             = f;
    delay(50);
}

/* ==========================================================================
 * Sample on both frequencies and return true if the reading at 'targetFreq'
 * really belongs to that beacon (section 7.4 of the guidelines: a strong
 * off-frequency beacon can leak into the 'wrong' tuning).
 * ========================================================================== */
bool confirmBeaconFrequency(int targetFreq){
    setFreq(targetFreq);
    ReadPD();
    int sumTarget = PD_sum;

    setFreq(1 - targetFreq);
    ReadPD();
    int sumOther = PD_sum;

    setFreq(targetFreq);   // leave tuned where the caller expects
    ReadPD();

    return (sumTarget >= sumOther);
}

/* ==========================================================================
 * One step of "go to whatever beacon is currently tuned in".
 *   Returns:
 *     -1  nothing seen (searching / spinning)
 *      0  driving toward it
 *     +1  we are on top of it (PD_sum > stop_level OR sonar < near_beacon_cm)
 * ========================================================================== */
int goToBeaconStep(){
    ReadPD();
    Find_max();
    showIRTelemetry();

    int error = 4 - max_no;                  // PD4 is straight ahead
    int steer = error * steer_sensitivity;
    int speed = forward_speed;

    if(PD_sum < ambient_level){              // search mode: slow spin to dwell
        drive(-search_spin_speed, search_spin_speed);
        return -1;
    }
    if(PD_sum > slow_level) speed = slow_speed;

    int sonar = SensorValue[sonarSensor];
    if(PD_sum > stop_level ||
       (sonar > 0 && sonar < near_beacon_cm)){
        stopDrive();
        return 1;
    }

    /* right motor gets +steer+speed; left gets -steer+speed so that a
       positive 'error' (max_no < 4, beacon to the left) turns us left. */
    drive(speed - steer, speed + steer);
    return 0;
}

/* ==========================================================================
 * Arm: drop onto the beacon pushbutton, then raise.  Uses the limit switch
 * at full-down as the primary stop, falls back to a timeout.
 * ========================================================================== */
void pressBeaconButton(){
    setStatusTop("ARM DOWN");
    ClearTimer(T1);
    motor[armMotor] = -60;
    while(SensorValue[armLimit] == 0 && time1[T1] < arm_drop_ms){ delay(10); }
    motor[armMotor] = 0;
    delay(400);                               // hold button down

    setStatusTop("ARM UP");
    ClearTimer(T1);
    motor[armMotor] = 60;
    while(time1[T1] < arm_raise_ms){ delay(10); }
    motor[armMotor] = 0;
}

/* ==========================================================================
 * Blind manoeuvres used between phases
 * ========================================================================== */
void backupFor(int ms){
    ClearTimer(T1);
    drive(-forward_speed, -forward_speed);
    while(time1[T1] < ms){ delay(10); }
    stopDrive();
}
void spinFor(int ms, int pwm){
    ClearTimer(T1);
    drive(-pwm, pwm);
    while(time1[T1] < ms){ delay(10); }
    stopDrive();
}

/* ==========================================================================
 * Phase 1+2: Find red beacon, stop, press button
 * ========================================================================== */
void phase_redBeacon(){
    setStatusTop("RED HUNT");
    setFreq(0);                               // 1 kHz, red

    /* Drive toward red until we're on top of it */
    while(true){
        int s = goToBeaconStep();
        if(s == 1){
            /* Double-check this is actually the red beacon and not
               green-bleed-through from close range */
            if(confirmBeaconFrequency(0)) break;
            /* If it was actually green leaking in, back up and keep looking */
            backupFor(300);
            spinFor(400, spin_speed);
        }
        /* Wall guard while hunting: if we bump, back up and turn */
        if(SensorValue[bumper] == 1){
            backupFor(backup_ms);
            spinFor(500, spin_speed);
        }
        delay(10);
    }

    stopDrive();
    setStatusTop("RED LOCK");
    pressBeaconButton();                      // turn the red beacon off
}

/* ==========================================================================
 * Phase 3+4: Find green beacon, capture it, push it out of the arena
 * ========================================================================== */
void phase_greenBeacon(){
    setStatusTop("BACKUP/TURN");
    backupFor(backup_ms);
    spinFor(turn_180_ms, spin_speed);

    setStatusTop("GREEN HUNT");
    setFreq(1);                               // 10 kHz, green

    while(true){
        int s = goToBeaconStep();
        if(s == 1){
            if(confirmBeaconFrequency(1)) break;
            backupFor(300);
            spinFor(400, spin_speed);
        }
        if(SensorValue[bumper] == 1){
            backupFor(backup_ms);
            spinFor(500, spin_speed);
        }
        delay(10);
    }

    setStatusTop("GREEN LOCK");

    /* Capture: drive in a little harder so the beacon is firmly in the
       scoop / against the front of the chassis. */
    ClearTimer(T1);
    drive(forward_speed, forward_speed);
    while(time1[T1] < 400){ delay(10); }

    setStatusTop("PUSH OUT");
    /* Push out: drive forward on the heading that just found the beacon.
       If the bumper trips we are against an arena wall (not the beacon),
       so back up, turn a bit, and keep pushing.  If the sonar shows a big
       open distance ahead, that's the arena opening - commit and run. */
    ClearTimer(T1);
    while(time1[T1] < push_out_ms){
        int sonar = SensorValue[sonarSensor];
        if(SensorValue[bumper] == 1){
            backupFor(400);
            spinFor(350, spin_speed);
            ClearTimer(T1);
            continue;
        }
        if(sonar == 0 || sonar > 80){
            /* Wide open in front = the opening. Full send. */
            drive(forward_speed + 20, forward_speed + 20);
        } else if(sonar < wall_cm){
            /* Wall coming - veer right */
            drive(forward_speed, forward_speed/2);
        } else {
            drive(forward_speed, forward_speed);
        }
        delay(20);
    }
    stopDrive();
}

/* ==========================================================================
 * Main
 * ========================================================================== */
task main(){
    setStatusTop("BOOT");
    stopDrive();
    motor[armMotor] = 0;
    SensorValue[exposeCtrl]   = 1;
    SensorValue[counterReset] = 1;
    SensorValue[counterReset] = 0;
    setFreq(0);
    delay(500);

    phase_redBeacon();      // Tasks 1 + 2
    phase_greenBeacon();    // Tasks 3 + 4

    setStatusTop("DONE");
    while(true){
        stopDrive();
        motor[armMotor] = 0;
        delay(100);
    }
}
